import { StyleSheet } from 'react-native';
import { colors, spacing, radius, fontSize, fontWeight } from '../theme';

export const userDetailModalStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background.overlay,
    padding: spacing.xl,
  },
  detailDialog: {
    width: '100%',
    maxWidth: 960,
    maxHeight: '92%',
    backgroundColor: colors.background.surface,
    borderRadius: radius.xxl,
    overflow: 'hidden',
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.lg,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
    backgroundColor: colors.background.surface,
  },
  detailTitle: {
    fontSize: fontSize.title,
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
  },
  detailSubtitle: {
    marginTop: spacing.xs,
    fontSize: fontSize.base,
    color: colors.text.muted,
    fontWeight: fontWeight.semibold,
  },
  headerCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.muted,
  },
  headerCloseText: {
    fontSize: fontSize.xl,
    color: colors.text.secondary,
    fontWeight: fontWeight.bold,
  },
  detailScroll: {
    flexGrow: 0,
  },
  detailContent: {
    padding: spacing.xxl,
  },
  bodyLayout: {
    gap: spacing.lg,
  },
  bodyLayoutMobile: {
    gap: spacing.sm,
  },
  bodyLayoutDesktop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.xl,
  },
  infoPanel: {
    gap: spacing.md,
  },
  infoPanelMobile: {
    gap: spacing.xs,
  },
  infoPanelDesktop: {
    flex: 1,
    minWidth: 0,
  },
  panelTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  detailGrid: {
    gap: spacing.sm + 2,
  },
  detailGridDesktop: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  detailField: {
    gap: spacing.xs,
  },
  detailFieldDesktop: {
    width: '48%',
    minWidth: 180,
    padding: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.background.subtle,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  detailFieldLabel: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.text.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  detailFieldValue: {
    fontSize: fontSize.base,
    lineHeight: 20,
    color: colors.text.primary,
    fontWeight: fontWeight.semibold,
  },
  mobileScreen: {
    paddingHorizontal: spacing.lg,
  },
  mobileBody: {
    flex: 1,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
  },
  mobileHeader: {
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderColor: colors.border.default,
    backgroundColor: colors.background.surface,
  },
  mobileHeaderTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
  },
  mobileContent: {
    flex: 1,
  },
  mobileActions: {
    marginTop: 'auto',
    paddingTop: spacing.md,
  },
  detailGridMobile: {
    gap: spacing.sm,
  },
  detailFieldMobile: {
    width: '100%',
    gap: 2,
  },
  detailFieldLabelMobile: {
    fontSize: fontSize.xs,
    letterSpacing: 0.2,
  },
  detailFieldValueMobile: {
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
  panelTitleMobile: {
    fontSize: fontSize.sm,
    marginBottom: 0,
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  statusRowMobile: {
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  badge: {
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: 6,
    borderRadius: radius.pill,
  },
  badgeMobile: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
  },
  badgeTextMobile: {
    fontSize: fontSize.xs,
  },
  badgeSuccess: { backgroundColor: colors.successLight },
  badgeWarning: { backgroundColor: colors.warningLight },
  badgeDanger: { backgroundColor: colors.dangerLight },
  badgeNeutral: { backgroundColor: colors.background.muted },
  badgeText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    textTransform: 'capitalize',
  },
  badgeTextSuccess: { color: colors.successDark },
  badgeTextWarning: { color: colors.warningDark },
  badgeTextDanger: { color: colors.dangerDark },
  badgeTextNeutral: { color: colors.text.secondary },
  documentSection: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.background.subtle,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  documentSectionMobile: {
    marginTop: spacing.sm,
    marginBottom: 0,
    padding: spacing.sm,
  },
  documentSectionDesktop: {
    flex: 1,
    minWidth: 0,
    marginTop: 0,
    marginBottom: 0,
  },
  documentTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.extrabold,
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  documentTitleMobile: {
    fontSize: fontSize.sm,
    marginBottom: spacing.xs,
  },
  documentImage: {
    width: '100%',
    height: 280,
    borderRadius: radius.md,
    backgroundColor: colors.border.default,
  },
  documentThumbnail: {
    width: '100%',
    aspectRatio: 1.586,
    borderRadius: radius.sm,
    backgroundColor: colors.border.default,
  },
  documentImageDesktop: {
    height: 360,
  },
  noDocument: {
    color: colors.text.muted,
    fontStyle: 'italic',
    paddingVertical: spacing.xxl,
    textAlign: 'center',
  },
  actions: {
    gap: spacing.sm + 2,
    marginTop: spacing.lg,
  },
  actionsMobile: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.sm,
  },
  actionsDesktop: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border.default,
  },
  btn: {
    paddingVertical: spacing.md + 2,
    borderRadius: radius.lg,
    alignItems: 'center',
  },
  btnMobile: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: 88,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
  },
  btnTextMobile: {
    fontSize: fontSize.sm,
  },
  btnDesktop: {
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.lg + 2,
    minWidth: 120,
  },
  btnText: { color: colors.text.inverse, fontWeight: fontWeight.bold, fontSize: fontSize.base },
  acceptBtn: { backgroundColor: colors.success },
  rejectBtn: { backgroundColor: colors.danger },
  deactivateBtn: { backgroundColor: colors.warning },
  activateBtn: { backgroundColor: colors.info },
  closeBtn: {
    backgroundColor: colors.background.surface,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  closeBtnText: { color: colors.text.secondary, fontWeight: fontWeight.bold, fontSize: fontSize.base },
  dialog: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.background.surface,
    borderRadius: radius.xl,
    padding: spacing.lg + 2,
  },
  dialogTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.extrabold,
    marginBottom: spacing.sm,
    color: colors.text.primary,
  },
  successTitle: {
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.extrabold,
    marginBottom: spacing.sm,
    color: colors.success,
  },
  dialogMessage: { marginBottom: spacing.lg, color: colors.text.secondary, lineHeight: 20 },
  dialogActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.sm + 2 },
  dialogBtn: {
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    minWidth: 88,
    alignItems: 'center',
  },
  dialogBtnCancel: { backgroundColor: colors.background.muted },
  dialogBtnCancelText: { color: colors.text.secondary, fontWeight: fontWeight.bold },
  dialogBtnConfirm: { backgroundColor: colors.success },
  btnDisabled: { opacity: 0.5 },
  selectWrap: {
    borderWidth: 1,
    borderColor: colors.border.default,
    borderRadius: radius.md,
    marginBottom: spacing.lg,
    overflow: 'hidden',
    backgroundColor: colors.background.surface,
  },
  selectTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md + 2,
  },
  selectTriggerText: {
    flex: 1,
    fontSize: fontSize.base,
    color: colors.text.primary,
    lineHeight: 20,
  },
  selectPlaceholder: {
    color: colors.text.muted,
  },
  selectChevron: {
    fontSize: fontSize.sm,
    color: colors.text.muted,
  },
  selectOptions: {
    borderTopWidth: 1,
    borderTopColor: colors.border.default,
    backgroundColor: colors.background.subtle,
  },
  selectOption: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md + 2,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
  },
  selectOptionSelected: {
    backgroundColor: colors.primaryLight,
  },
  selectOptionText: {
    fontSize: fontSize.base,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  selectOptionTextSelected: {
    color: colors.primaryDark,
    fontWeight: fontWeight.bold,
  },
});
