import { StyleSheet } from 'react-native';

export const residentHomeStyles = StyleSheet.create({
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
  },
  card: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 12,
    boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.05)',
    marginBottom: 16,
  },
  verifiedCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#10b981',
    backgroundColor: '#ecfdf5',
  },
  actionCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
  },
  cardTitleSuccess: {
    fontWeight: '700',
    color: '#065f46',
    fontSize: 15,
    marginBottom: 4,
  },
  cardTitleWarning: {
    fontWeight: '700',
    color: '#92400e',
    fontSize: 15,
    marginBottom: 4,
  },
  cardDesc: {
    color: '#4b5563',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  input: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#111827',
    marginBottom: 10,
  },
  uploadButton: {
    backgroundColor: '#e5e7eb',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
  },
  uploadButtonText: {
    color: '#374151',
    fontWeight: '600',
    fontSize: 14,
  },
  previewImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    marginBottom: 10,
  },
  accentButton: {
    backgroundColor: '#4f46e5',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  accentButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  hotlineCard: {
    backgroundColor: '#ffffff',
    padding: 14,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.05)',
  },
  hotlineName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    flex: 1,
    marginRight: 8,
  },
  hotlinePhone: {
    fontSize: 14,
    color: '#ef4444',
    fontWeight: '700',
  },
  faqBlock: {
    marginBottom: 16,
    backgroundColor: '#ffffff',
    padding: 14,
    borderRadius: 10,
    boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.05)',
  },
  faqQuestion: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 4,
  },
  faqAnswer: {
    fontSize: 13,
    color: '#4b5563',
    lineHeight: 18,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pendingCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
    backgroundColor: '#fffbeb',
  },
  rejectedCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#ef4444',
    backgroundColor: '#fef2f2',
  },
  cardTitlePending: {
    fontWeight: '700',
    color: '#92400e',
    fontSize: 15,
    marginBottom: 4,
  },
  cardTitleError: {
    fontWeight: '700',
    color: '#991b1b',
    fontSize: 15,
    marginBottom: 4,
  },
  remarksContainer: {
    backgroundColor: '#fee2e2',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#ef4444',
  },
  remarksLabel: {
    fontWeight: '700',
    color: '#991b1b',
    fontSize: 12,
    marginBottom: 4,
  },
  remarksText: {
    color: '#7f1d1d',
    fontSize: 13,
    lineHeight: 18,
  },
  fieldLabel: {
    fontSize: 13,
    color: '#4b5563',
    fontWeight: '700',
    marginBottom: 8,
  },
  summaryContainer: {
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    padding: 12,
    marginBottom: 10,
  },
  summaryText: {
    color: '#111827',
    fontSize: 14,
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    marginBottom: 10,
  },
  fileSummary: {
    backgroundColor: '#eef2ff',
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  fileName: {
    color: '#1e3a8a',
    fontWeight: '700',
    marginBottom: 4,
  },
  fileSize: {
    color: '#475569',
    fontSize: 13,
  },
  backButton: {
    marginTop: 10,
    borderColor: '#4b46e5',
    borderWidth: 1,
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  backButtonText: {
    color: '#4b46e5',
    fontWeight: '700',
  },
});
